In [2]:
import numpy as np
from keras.utils import np_utils


Using TensorFlow backend.


In [13]:
seg_img

array([[0, 2, 1, 0, 0, 0, 0, 0, 2, 0],
       [2, 2, 1, 2, 1, 1, 1, 0, 1, 2],
       [1, 0, 1, 2, 0, 0, 2, 0, 1, 0],
       [2, 2, 2, 2, 1, 0, 2, 2, 1, 2],
       [0, 2, 2, 1, 2, 0, 1, 0, 1, 2],
       [1, 1, 2, 0, 1, 1, 2, 0, 2, 1],
       [1, 1, 1, 0, 2, 2, 0, 0, 0, 2],
       [2, 2, 0, 1, 0, 0, 1, 2, 2, 1],
       [1, 0, 0, 2, 0, 2, 0, 0, 0, 2],
       [1, 0, 1, 0, 2, 0, 0, 0, 2, 2]])

In [8]:
seg_img=np.random.randint(0,3,(10,10))
seg_catego=np_utils.to_categorical(seg_img, num_classes=3)
seg_catego.shape

(10, 10, 3)

In [11]:
seg_catego

array([[[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
  

In [12]:
np.argmax(seg_catego,axis=2)

array([[0, 2, 1, 0, 0, 0, 0, 0, 2, 0],
       [2, 2, 1, 2, 1, 1, 1, 0, 1, 2],
       [1, 0, 1, 2, 0, 0, 2, 0, 1, 0],
       [2, 2, 2, 2, 1, 0, 2, 2, 1, 2],
       [0, 2, 2, 1, 2, 0, 1, 0, 1, 2],
       [1, 1, 2, 0, 1, 1, 2, 0, 2, 1],
       [1, 1, 1, 0, 2, 2, 0, 0, 0, 2],
       [2, 2, 0, 1, 0, 0, 1, 2, 2, 1],
       [1, 0, 0, 2, 0, 2, 0, 0, 0, 2],
       [1, 0, 1, 0, 2, 0, 0, 0, 2, 2]], dtype=int64)