In [2]:
from tensorflow.python.keras import backend as K
import tensorflow as tf
import numpy as np
from tensorflow.python import keras

In [9]:
np.random.randint(0,3,(25,25,3))

array([[[0, 1, 0],
        [1, 1, 2],
        [0, 2, 2],
        ...,
        [1, 0, 2],
        [0, 0, 2],
        [1, 1, 2]],

       [[2, 1, 2],
        [2, 1, 2],
        [2, 1, 1],
        ...,
        [1, 0, 1],
        [2, 1, 0],
        [2, 1, 0]],

       [[0, 0, 0],
        [1, 0, 2],
        [0, 2, 0],
        ...,
        [1, 2, 1],
        [1, 2, 0],
        [0, 0, 2]],

       ...,

       [[1, 2, 2],
        [1, 2, 0],
        [0, 2, 2],
        ...,
        [2, 1, 1],
        [1, 2, 1],
        [1, 1, 2]],

       [[1, 0, 0],
        [2, 2, 0],
        [0, 1, 0],
        ...,
        [0, 1, 2],
        [2, 1, 0],
        [0, 2, 2]],

       [[2, 2, 2],
        [1, 0, 0],
        [0, 1, 0],
        ...,
        [2, 2, 2],
        [2, 0, 1],
        [2, 0, 1]]])

In [11]:
val=np.random.random((25,25,3))
val=K.variable(value=val)

#array([001,002...])となる
val=K.flatten(val)

#tf->numpy
K.eval(val)

array([0.276241  , 0.41575825, 0.69500095, ..., 0.9741741 , 0.19416422,
       0.7080688 ], dtype=float32)

In [17]:
y_true=K.ones((3,3,3,3))
y_pred=K.ones((3,3,3,3))
def dice_coef(y_true, y_pred):
    y_true = K.flatten(y_true)
    y_pred = K.flatten(y_pred)
    intersection = K.sum(y_true * y_pred)
    print(K.eval(intersection))
    return 2.0 * intersection / (K.sum(y_true) + K.sum(y_pred) + 1)

K.eval(dice_coef(y_true, y_pred))

81.0


0.993865

In [18]:
def dice_1(y_true, y_pred):
    K = tf.keras.backend

    eps = K.constant(1e-6)

    truelabels = K.cast(y_true[:, :, :, 1], tf.int32)
    predictions = K.cast(y_pred[:, :, :, 1], tf.int32)

    #真理値からなるテンソルを返す→最小値を取る→合計する
    intersection = K.cast(K.sum(K.minimum(K.cast(K.equal(predictions, truelabels), tf.int32), truelabels)), tf.float32)
    union = tf.count_nonzero(predictions, dtype=tf.float32) + tf.count_nonzero(truelabels, dtype=tf.float32)
    dice_1 = 2 * intersection / (union + eps)

    return dice_1

K.eval(dice_1(y_true, y_pred))

1.0

In [19]:
a=tf.constant([0,2,2,1])
# b=tf.constant([0,2,2,1])
K.eval(tf.where(a==2,2,0))

ValueError: Shapes must be equal rank, but are 1 and 0 for 'Select_12' (op: 'Select') with input shapes: [], [4], [].

In [18]:
K.eval(tf.equal(a,b))

array([ True,  True,  True, False])

In [ ]:
tf.where()

In [25]:
true=K.ones((3,3,3,3))
K.eval(tf.where(K.cast(true[:,:,:,1], tf.int32)))

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 1, 0],
       [0, 1, 1],
       [0, 1, 2],
       [0, 2, 0],
       [0, 2, 1],
       [0, 2, 2],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 2],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 2],
       [1, 2, 0],
       [1, 2, 1],
       [1, 2, 2],
       [2, 0, 0],
       [2, 0, 1],
       [2, 0, 2],
       [2, 1, 0],
       [2, 1, 1],
       [2, 1, 2],
       [2, 2, 0],
       [2, 2, 1],
       [2, 2, 2]])

In [32]:
K.eval(tf.cast(K.equal(true,1),tf.int32))

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]], dtype=int32)